# Generated by Django 5.0.2 on 2024-02-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_item_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='parent',
            new_name='children',
        ),
    ]
