# Generated by Django 5.0.2 on 2024-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_parent_item_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_main',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
