# Generated by Django 5.0.2 on 2024-02-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_item_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='children',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_main',
        ),
    ]
