# Generated by Django 5.0.2 on 2024-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_children_item_parent_remove_item_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
