# Generated by Django 5.0.2 on 2024-02-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_itemrec_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemRec',
        ),
    ]
